spring.datasource.url=jdbc:sqlite:mcu-tierlist.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.thymeleaf.cache=false
server.servlet.session.timeout=4h
server.servlet.session.cookie.max-age=14400
